# Generated by Django 4.1.5 on 2023-05-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djproject', '0002_stategraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='vk_key',
            field=models.CharField(max_length=100),
        ),
    ]
